# Generated by Django 3.1.8 on 2021-04-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athletes',
            options={'verbose_name_plural': 'Athletes'},
        ),
        migrations.RenameField(
            model_name='athletes',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='full_name',
            new_name='name',
        ),
    ]
