# Generated by Django 3.1.8 on 2021-04-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20210427_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletes',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='athletes',
            name='social_url2',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='social_url2',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
