# Generated by Django 3.1.8 on 2021-04-16 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210414_1209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessories',
            options={'verbose_name_plural': 'Accessories'},
        ),
        migrations.AlterModelOptions(
            name='clothing',
            options={'verbose_name_plural': 'Clothing'},
        ),
        migrations.CreateModel(
            name='Footwear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('size', models.CharField(choices=[('S', 'UK 6-8'), ('M', 'UK 8-10'), ('L', 'UK 10+')], default='choose your size', max_length=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
            options={
                'verbose_name_plural': 'Footwear',
            },
        ),
    ]
