# Generated by Django 3.1.8 on 2021-04-16 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210416_1810'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clothing',
            new_name='Product',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
    ]
