# Generated by Django 3.1.8 on 2021-04-18 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210416_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footwear',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.DeleteModel(
            name='Accessories',
        ),
        migrations.DeleteModel(
            name='Footwear',
        ),
    ]
